matrix:
  include:
    # for android    
    - os: linux
      language: android
      sudo: required
      env:
        - BUILD_TARGET=Android      
        - ANDROID_SDK_ROOT=/usr/local/android-sdk
script:
  - python main.py

cache:
  bundler: true

notifications:
  email: false