matrix:
  include:
    # for android    
    - os: linux
      language: android      

before_install:
  # Install NDK and cmake via android sdkmanager. Unfortunately to acknowledge the licenses
  # takes a while. Looks like the "echo y" solution is not working. Needs improvement!
  - export TERM=dumb
  - touch ~/.android/repositories.cfg
  - mkdir -p /usr/local/android-sdk/licenses
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > /usr/local/android-sdk/licenses/android-sdk-license
  - echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" >> /usr/local/android-sdk/licenses/android-sdk-license
 
  # Install NDK and cmake via android sdkmanager.
  - export ANDROID_SDK_ROOT=/usr/local/android-sdk
  - /usr/local/android-sdk/tools/bin/sdkmanager --update > /dev/null
  - echo "y" | /usr/local/android-sdk/tools/bin/sdkmanager  "ndk-bundle" "cmake;3.6.4111459" > /dev/null

script:
  - which android
  - git clone https://github.com/yuangu/sxtwl_cpp.git
  - cd sxtwl_cpp
  - python ndk_build.py

cache:
  bundler: true

notifications:
  email: false