matrix:
  include:
    # for android    
    - os: linux
      language: android
      sudo: required
      env:
        - BUILD_TARGET=Android      
        - ANDROID_SDK_ROOT=/usr/local/android-sdk
      before_install:
        - if [ ! -z "$QT" ] ; then
            sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa ;
          fi
        - sudo apt-get update -qq
        - sudo apt-get install -q swig 
script:
  - python main.py $BUILD_TARGET

cache:
  bundler: true

notifications:
  email: false