matrix:
  include:
    # for android    
    - os: linux
      language: android
      sudo: required
      env:
        - BUILD_TARGET=Android      
        - ANDROID_SDK_ROOT=/usr/local/android-sdk
      before_install:      
        - sudo apt-get update -qq
        - sudo apt-get install -q python-pip
        - sudo apt-get install -q swig 
        - sudo python -m pip install pycrypto
        - sudo python -m pip install pycryptodome
        - sudo python -m pip install requests_toolbelt
script:
  - python main.py $BUILD_TARGET

cache:
  bundler: true

notifications:
  email: false