matrix:
  include:
    # for android    
    - os: linux
      language: android
      env: BUILD_TARGET=Android      

script:
  - python main.py

cache:
  bundler: true

notifications:
  email: false